// Single source of truth for both Office add-in manifests (dev manifest.xml,
// prod manifest.prod.xml). Owns all host, URL, and copy data; manifest/xml.ts
// only renders it. Invariant: both environments share one AddinSpec (same
// GUID, same hosts) - only ManifestEnvironment (base URL, header comment) differs.

import pkg from "../package.json" with { type: "json" };

export interface ManifestEnvironment {
  name: "dev" | "prod";
  file: string;
  baseUrl: string;
  comment: string;
}

export interface ButtonSpec {
  id: string; // e.g. "Autocolor" -> control id SMT.Button.Autocolor
  label: string;
  tip: string;
  action: { kind: "showPane" } | { kind: "function"; name: string };
}

export interface HostSpec {
  name: "Workbook" | "Presentation";
  page: string; // pane html served from baseUrl
  urlResid: string; // resource id of the pane URL
  taskpaneId: string;
  groupId: string;
  groupLabel: string;
  buttons: ButtonSpec[];
}

export interface AddinSpec {
  id: string;
  version: string; // "X.Y.Z.0", derived from package.json
  provider: string;
  displayName: string;
  description: string;
  supportUrl: string;
  appDomain: string;
  tabLabel: string;
  iconResids: { 16: string; 32: string; 80: string };
  hosts: HostSpec[];
}

export const ENVIRONMENTS: readonly ManifestEnvironment[] = [
  {
    name: "dev",
    file: "manifest.xml",
    baseUrl: "https://localhost:3000/",
    comment:
      "Development manifest: same GUID as manifest.prod.xml (same add-in identity), only URLs differ.\n" +
      "     Sideloaded by npm start; the pane is served by vite on https://localhost:3000/.\n" +
      "     GENERATED by scripts/build-manifests.ts from manifest/spec.ts - do not edit by hand.",
  },
  {
    name: "prod",
    file: "manifest.prod.xml",
    baseUrl: "https://dbautomatizacijas.com/modelis/",
    comment:
      "Production manifest: same GUID as manifest.xml (same add-in identity), only URLs differ.\n" +
      "     Served LIVE from https://dbautomatizacijas.com/modelis/ (suite key modelis, Rust host :8804).\n" +
      "     The path carries a Cloudflare Access bypass - Office webviews cannot pass Access\n" +
      "     (docs/research/launch-path.md), so only built pane assets may live there.",
  },
];

export const WORKBOOK_HOST: HostSpec = {
  name: "Workbook",
  page: "taskpane.html",
  urlResid: "SMT.Taskpane.Url",
  taskpaneId: "SMT.Taskpane",
  groupId: "SMT.Group.Tools",
  groupLabel: "Model Tools",
  buttons: [
    {
      id: "OpenPane",
      label: "Model Tools",
      tip: "Open the Model Tools task pane.",
      action: { kind: "showPane" },
    },
    {
      id: "Autocolor",
      label: "Autocolor",
      tip: "Color inputs, formulas and links in your palette.",
      action: { kind: "function", name: "SMT_AUTOCOLOR" },
    },
    {
      id: "FillRight",
      label: "Fill Right",
      tip: "Fill the formula from the left cell across the selection.",
      action: { kind: "function", name: "SMT_FILLRIGHT" },
    },
    {
      id: "FillDown",
      label: "Fill Down",
      tip: "Fill the formula from the top cell down the selection.",
      action: { kind: "function", name: "SMT_FILLDOWN" },
    },
    {
      id: "IfError",
      label: "IFERROR",
      tip: "Wrap selected formulas with IFERROR.",
      action: { kind: "function", name: "SMT_IFERROR" },
    },
  ],
};

export const PRESENTATION_HOST: HostSpec = {
  name: "Presentation",
  page: "pptpane.html",
  urlResid: "SMT.Pptpane.Url",
  taskpaneId: "SMT.Pptpane",
  groupId: "SMT.Group.Links",
  groupLabel: "Model Tools Links",
  buttons: [
    {
      id: "OpenLinks",
      label: "Links",
      tip: "Open the Model Tools linked-objects pane.",
      action: { kind: "showPane" },
    },
  ],
};

const packageVersion = pkg.version;

export const ADDIN: AddinSpec = {
  id: "FF1B34D8-DD7D-4B39-8FA9-6248CA09DB6E",
  version: `${packageVersion}.0`,
  provider: "Daniels Bendiks",
  displayName: "Model Tools",
  description: "Fast, consistent financial modelling tools for Excel.",
  supportUrl: "https://dbautomatizacijas.com",
  appDomain: "https://dbautomatizacijas.com",
  tabLabel: "Model Tools",
  iconResids: { 16: "SMT.Icon.16", 32: "SMT.Icon.32", 80: "SMT.Icon.80" },
  hosts: [WORKBOOK_HOST, PRESENTATION_HOST],
};
