// Single source of truth for both Office add-in manifests (dev manifest.xml,
// prod manifest.prod.xml). Owns all host, URL, and copy data; manifest/xml.ts
// only renders it. Invariant: both environments share one AddinSpec (same
// GUID, same hosts) - only ManifestEnvironment (base URL, header comment) differs.

import pkg from "../package.json" with { type: "json" };

export interface ManifestEnvironment {
  name: "dev" | "prod";
  file: string;
  baseUrl: string;
  comment: string;
}

export interface ButtonSpec {
  id: string; // e.g. "Autocolor" -> control id SMT.Button.Autocolor
  label: string;
  tip: string;
  action: { kind: "showPane" } | { kind: "function"; name: string };
}

export interface GroupSpec {
  id: string; // e.g. "SMT.Group.Audit" -> resource id SMT.Group.Audit.Label
  label: string;
  buttons: ButtonSpec[];
}

// Excel custom functions (=SMT.ROUND, =SMT.ROUNDSUM): the script and the
// registration JSON Office loads, plus the namespace it prefixes to every
// function name. They run in the pane's own shared runtime, so there is no
// second runtime and no second page - docs/research/custom-functions.md.
export interface CustomFunctionsSpec {
  namespace: string;
  namespaceResid: string;
  scriptFile: string;
  scriptResid: string;
  metadataFile: string;
  metadataResid: string;
}

export interface HostSpec {
  name: "Workbook" | "Presentation";
  page: string; // pane html served from baseUrl
  urlResid: string; // resource id of the pane URL
  taskpaneId: string;
  // Excel only: PowerPoint has no custom functions.
  customFunctions?: CustomFunctionsSpec;
  groups: GroupSpec[];
}

export interface AddinSpec {
  id: string;
  version: string; // "X.Y.Z.0", derived from package.json
  provider: string;
  displayName: string;
  description: string;
  supportUrl: string;
  appDomain: string;
  tabLabel: string;
  iconResids: { 16: string; 32: string; 80: string };
  hosts: HostSpec[];
}

export const ENVIRONMENTS: readonly ManifestEnvironment[] = [
  {
    name: "dev",
    file: "manifest.xml",
    baseUrl: "https://localhost:3000/",
    comment:
      "Development manifest: same GUID as manifest.prod.xml (same add-in identity), only URLs differ.\n" +
      "     Sideloaded by npm start; the pane is served by vite on https://localhost:3000/.\n" +
      "     GENERATED by scripts/build-manifests.ts from manifest/spec.ts - do not edit by hand.",
  },
  {
    name: "prod",
    file: "manifest.prod.xml",
    baseUrl: "https://dbautomatizacijas.com/modelis/",
    comment:
      "Production manifest: same GUID as manifest.xml (same add-in identity), only URLs differ.\n" +
      "     Served LIVE from https://dbautomatizacijas.com/modelis/ (suite key modelis, Rust host :8804).\n" +
      "     The path carries a Cloudflare Access bypass - Office webviews cannot pass Access\n" +
      "     (docs/research/launch-path.md), so only built pane assets may live there.",
  },
];

export const WORKBOOK_HOST: HostSpec = {
  name: "Workbook",
  page: "taskpane.html",
  urlResid: "SMT.Taskpane.Url",
  taskpaneId: "SMT.Taskpane",
  customFunctions: {
    namespace: "SMT",
    namespaceResid: "SMT.Functions.Namespace",
    scriptFile: "functions.js",
    scriptResid: "SMT.Functions.Script.Url",
    metadataFile: "functions.json",
    metadataResid: "SMT.Functions.Metadata.Url",
  },
  groups: [
    {
      id: "SMT.Group.Tools",
      label: "Model Tools",
      buttons: [
        {
          id: "OpenPane",
          label: "Model Tools",
          tip: "Open the Model Tools task pane.",
          action: { kind: "showPane" },
        },
        {
          id: "Autocolor",
          label: "Autocolor",
          tip: "Color inputs, formulas and links in your palette.",
          action: { kind: "function", name: "SMT_AUTOCOLOR" },
        },
        {
          id: "FillRight",
          label: "Fill Right",
          tip: "Fill the formula from the left cell across the selection.",
          action: { kind: "function", name: "SMT_FILLRIGHT" },
        },
        {
          id: "FillDown",
          label: "Fill Down",
          tip: "Fill the formula from the top cell down the selection.",
          action: { kind: "function", name: "SMT_FILLDOWN" },
        },
        {
          id: "IfError",
          label: "IFERROR",
          tip: "Wrap selected formulas with IFERROR.",
          action: { kind: "function", name: "SMT_IFERROR" },
        },
      ],
    },
    {
      id: "SMT.Group.Audit",
      label: "Audit",
      buttons: [
        {
          id: "Audit",
          label: "Audit overlay",
          tip: "Toggle the formula consistency overlay.",
          action: { kind: "function", name: "SMT_AUDIT" },
        },
        {
          id: "TracePre",
          label: "Precedents",
          tip: "Jump to the direct precedents of the active cell.",
          action: { kind: "function", name: "SMT_TRACE_PRE" },
        },
        {
          id: "TraceDep",
          label: "Dependents",
          tip: "Jump to the direct dependents of the active cell.",
          action: { kind: "function", name: "SMT_TRACE_DEP" },
        },
      ],
    },
    {
      id: "SMT.Group.Paste",
      label: "Paste",
      buttons: [
        {
          id: "Undo",
          label: "SMT Undo",
          tip: "Restore the last range changed by Model Tools.",
          action: { kind: "function", name: "SMT_UNDO" },
        },
        {
          id: "PasteValues",
          label: "Paste values",
          tip: "Paste the copied source as values.",
          action: { kind: "function", name: "SMT_PASTE_VALUES" },
        },
        {
          id: "PasteFormats",
          label: "Paste formats",
          tip: "Paste the copied source's formats only.",
          action: { kind: "function", name: "SMT_PASTE_FORMATS" },
        },
      ],
    },
    {
      id: "SMT.Group.Model",
      label: "Model",
      buttons: [
        {
          id: "Cagr",
          label: "CAGR",
          tip: "Insert a CAGR formula for the selection.",
          action: { kind: "function", name: "SMT_CAGR" },
        },
        {
          id: "Sign",
          label: "Sign flip",
          tip: "Flip the sign of the selected formulas and values.",
          action: { kind: "function", name: "SMT_SIGN" },
        },
        {
          id: "ScaleUp",
          label: "x1000",
          tip: "Scale the selection up by a thousand.",
          action: { kind: "function", name: "SMT_SCALEUP" },
        },
        {
          id: "ScaleDown",
          label: "/1000",
          tip: "Scale the selection down by a thousand.",
          action: { kind: "function", name: "SMT_SCALEDOWN" },
        },
      ],
    },
    {
      id: "SMT.Group.Workbook",
      label: "Workbook",
      buttons: [
        {
          id: "Waterfall",
          label: "Waterfall",
          tip: "Build a waterfall chart from the selected bridge table.",
          action: { kind: "function", name: "SMT_WATERFALL" },
        },
        {
          id: "Toc",
          label: "Contents sheet",
          tip: "Insert or refresh the workbook contents sheet.",
          action: { kind: "function", name: "SMT_TOC" },
        },
      ],
    },
  ],
};

export const PRESENTATION_HOST: HostSpec = {
  name: "Presentation",
  page: "pptpane.html",
  urlResid: "SMT.Pptpane.Url",
  taskpaneId: "SMT.Pptpane",
  groups: [
    {
      id: "SMT.Group.Links",
      label: "Model Tools Links",
      buttons: [
        {
          id: "OpenLinks",
          label: "Links",
          tip: "Open the Model Tools linked-objects pane.",
          action: { kind: "showPane" },
        },
      ],
    },
  ],
};

const packageVersion = pkg.version;

export const ADDIN: AddinSpec = {
  id: "FF1B34D8-DD7D-4B39-8FA9-6248CA09DB6E",
  version: `${packageVersion}.0`,
  provider: "Daniels Bendiks",
  displayName: "Model Tools",
  description:
    "Fast, consistent financial modelling tools for Excel and PowerPoint.",
  supportUrl: "https://dbautomatizacijas.com",
  appDomain: "https://dbautomatizacijas.com",
  tabLabel: "Model Tools",
  iconResids: { 16: "SMT.Icon.16", 32: "SMT.Icon.32", 80: "SMT.Icon.80" },
  hosts: [WORKBOOK_HOST, PRESENTATION_HOST],
};
