// Single source of truth for both Office add-in manifests (dev manifest.xml,
// prod manifest.prod.xml). Owns all host, URL, and copy data; manifest/xml.ts
// only renders it. Invariant: both environments share one AddinSpec (same
// GUID, same hosts) - only ManifestEnvironment (base URL, header comment) differs.

import pkg from "../package.json" with { type: "json" };

export interface ManifestEnvironment {
  name: "dev" | "prod";
  file: string;
  baseUrl: string;
  comment: string;
}

export interface ButtonSpec {
  id: string; // e.g. "Autocolor" -> control id PLSFIX.Button.Autocolor
  label: string;
  tip: string;
  // A semantic name from public/assets/ribbon. Commands deliberately have
  // their own artwork: Office's ribbon is visual at a glance, while the app
  // mark remains the icon for the add-in and its groups.
  icon: RibbonIcon;
  action: { kind: "showPane" } | { kind: "function"; name: string };
}

export type RibbonIcon =
  | "audit"
  | "cagr"
  | "dependents"
  | "fill-down"
  | "fill-right"
  | "guard"
  | "links"
  | "palette"
  | "pane"
  | "paste-formats"
  | "paste-values"
  | "precedents"
  | "scale-down"
  | "scale-up"
  | "sign"
  | "toc"
  | "undo"
  | "waterfall"
  // PowerPoint: the Tools tab's object tools and the arrange commands.
  | "objects"
  | "match-size"
  | "select-similar"
  | "swap"
  | "capture-style"
  | "apply-style"
  | "align-left"
  | "align-center"
  | "align-right"
  | "align-top"
  | "align-middle"
  | "align-bottom"
  | "distribute-across"
  | "distribute-down";

export interface GroupSpec {
  id: string; // e.g. "PLSFIX.Group.Audit" -> resource id PLSFIX.Group.Audit.Label
  label: string;
  buttons: ButtonSpec[];
}

// Excel custom functions (=PLSFIX.ROUND, =PLSFIX.ROUNDSUM): the script and the
// registration JSON Office loads, plus the namespace it prefixes to every
// function name. They run in the pane's own shared runtime, so there is no
// second runtime and no second page - docs/research/custom-functions.md.
export interface CustomFunctionsSpec {
  namespace: string;
  namespaceResid: string;
  scriptFile: string;
  scriptResid: string;
  metadataFile: string;
  metadataResid: string;
}

export interface HostSpec {
  name: "Workbook" | "Presentation";
  page: string; // pane html served from baseUrl
  urlResid: string; // resource id of the pane URL
  taskpaneId: string;
  // Excel only: PowerPoint has no custom functions.
  customFunctions?: CustomFunctionsSpec;
  groups: GroupSpec[];
}

export interface AddinSpec {
  id: string;
  version: string; // "X.Y.Z.0", derived from package.json
  provider: string;
  displayName: string;
  description: string;
  supportUrl: string;
  appDomain: string;
  tabLabel: string;
  iconResids: { 16: string; 32: string; 80: string };
  hosts: HostSpec[];
}

export const ENVIRONMENTS: readonly ManifestEnvironment[] = [
  {
    name: "dev",
    file: "manifest.xml",
    baseUrl: "https://localhost:3000/",
    comment:
      "Development manifest: same GUID as manifest.prod.xml (same add-in identity), only URLs differ.\n" +
      "     Sideloaded by npm start; the pane is served by vite on https://localhost:3000/.\n" +
      "     GENERATED by scripts/build-manifests.ts from manifest/spec.ts - do not edit by hand.",
  },
  {
    name: "prod",
    file: "manifest.prod.xml",
    baseUrl: "https://dbautomatizacijas.com/modelis/",
    comment:
      "Production manifest: same GUID as manifest.xml (same add-in identity), only URLs differ.\n" +
      "     Served LIVE from https://dbautomatizacijas.com/modelis/ (suite key modelis, Rust host :8804).\n" +
      "     The path carries a Cloudflare Access bypass - Office webviews cannot pass Access\n" +
      "     (docs/research/launch-path.md), so only built pane assets may live there.",
  },
];

export const WORKBOOK_HOST: HostSpec = {
  name: "Workbook",
  page: "taskpane.html",
  urlResid: "PLSFIX.Taskpane.Url",
  taskpaneId: "PLSFIX.Taskpane",
  customFunctions: {
    namespace: "PLSFIX",
    namespaceResid: "PLSFIX.Functions.Namespace",
    scriptFile: "functions.js",
    scriptResid: "PLSFIX.Functions.Script.Url",
    metadataFile: "functions.json",
    metadataResid: "PLSFIX.Functions.Metadata.Url",
  },
  groups: [
    {
      id: "PLSFIX.Group.Tools",
      label: "Model Tools",
      buttons: [
        {
          id: "OpenPane",
          label: "Model Tools",
          tip: "Open the pls,fix task pane.",
          icon: "pane",
          action: { kind: "showPane" },
        },
        {
          id: "Autocolor",
          label: "Autocolor",
          tip: "Color inputs, formulas and links in your palette.",
          icon: "palette",
          action: { kind: "function", name: "PLSFIX_AUTOCOLOR" },
        },
        {
          id: "FillRight",
          label: "Fill Right",
          tip: "Fill the formula from the left cell across the selection.",
          icon: "fill-right",
          action: { kind: "function", name: "PLSFIX_FILLRIGHT" },
        },
        {
          id: "FillDown",
          label: "Fill Down",
          tip: "Fill the formula from the top cell down the selection.",
          icon: "fill-down",
          action: { kind: "function", name: "PLSFIX_FILLDOWN" },
        },
        {
          id: "IfError",
          label: "IFERROR",
          tip: "Wrap selected formulas with IFERROR.",
          icon: "guard",
          action: { kind: "function", name: "PLSFIX_IFERROR" },
        },
      ],
    },
    {
      id: "PLSFIX.Group.Audit",
      label: "Audit",
      buttons: [
        {
          id: "Audit",
          label: "Audit overlay",
          tip: "Toggle the formula consistency overlay.",
          icon: "audit",
          action: { kind: "function", name: "PLSFIX_AUDIT" },
        },
        {
          id: "TracePre",
          label: "Precedents",
          tip: "Jump to the direct precedents of the active cell.",
          icon: "precedents",
          action: { kind: "function", name: "PLSFIX_TRACE_PRE" },
        },
        {
          id: "TraceDep",
          label: "Dependents",
          tip: "Jump to the direct dependents of the active cell.",
          icon: "dependents",
          action: { kind: "function", name: "PLSFIX_TRACE_DEP" },
        },
      ],
    },
    {
      id: "PLSFIX.Group.Paste",
      label: "Paste",
      buttons: [
        {
          id: "Undo",
          label: "pls,fix Undo",
          tip: "Restore the last range changed by pls,fix.",
          icon: "undo",
          action: { kind: "function", name: "PLSFIX_UNDO" },
        },
        {
          id: "PasteValues",
          label: "Paste values",
          tip: "Paste the copied source as values.",
          icon: "paste-values",
          action: { kind: "function", name: "PLSFIX_PASTE_VALUES" },
        },
        {
          id: "PasteFormats",
          label: "Paste formats",
          tip: "Paste the copied source's formats only.",
          icon: "paste-formats",
          action: { kind: "function", name: "PLSFIX_PASTE_FORMATS" },
        },
      ],
    },
    {
      id: "PLSFIX.Group.Model",
      label: "Model",
      buttons: [
        {
          id: "Cagr",
          label: "CAGR",
          tip: "Insert a CAGR formula for the selection.",
          icon: "cagr",
          action: { kind: "function", name: "PLSFIX_CAGR" },
        },
        {
          id: "Sign",
          label: "Sign flip",
          tip: "Flip the sign of the selected formulas and values.",
          icon: "sign",
          action: { kind: "function", name: "PLSFIX_SIGN" },
        },
        {
          id: "ScaleUp",
          label: "x1000",
          tip: "Scale the selection up by a thousand.",
          icon: "scale-up",
          action: { kind: "function", name: "PLSFIX_SCALEUP" },
        },
        {
          id: "ScaleDown",
          label: "/1000",
          tip: "Scale the selection down by a thousand.",
          icon: "scale-down",
          action: { kind: "function", name: "PLSFIX_SCALEDOWN" },
        },
      ],
    },
    {
      id: "PLSFIX.Group.Workbook",
      label: "Workbook",
      buttons: [
        {
          id: "Waterfall",
          label: "Waterfall",
          tip: "Build a waterfall chart from the selected bridge table.",
          icon: "waterfall",
          action: { kind: "function", name: "PLSFIX_WATERFALL" },
        },
        {
          id: "Toc",
          label: "Contents sheet",
          tip: "Insert or refresh the workbook contents sheet.",
          icon: "toc",
          action: { kind: "function", name: "PLSFIX_TOC" },
        },
      ],
    },
  ],
};

export const PRESENTATION_HOST: HostSpec = {
  name: "Presentation",
  page: "pptpane.html",
  urlResid: "PLSFIX.Pptpane.Url",
  taskpaneId: "PLSFIX.Pptpane",
  groups: [
    {
      id: "PLSFIX.Group.Links",
      label: "Links",
      buttons: [
        {
          id: "OpenLinks",
          label: "Links",
          tip: "Open the pls,fix linked-objects pane.",
          icon: "links",
          action: { kind: "showPane" },
        },
      ],
    },
    // The Tools tab's parameterless tools, one click from the ribbon; the
    // pane's own selects stay the home of the direction-bound ones, which
    // the Arrange group spells out button by button below.
    {
      id: "PLSFIX.Group.Objects",
      label: "Objects",
      buttons: [
        {
          id: "ObjectTools",
          label: "Object tools",
          tip: "Open the pls,fix pane on its Tools tab.",
          icon: "objects",
          action: { kind: "function", name: "PLSFIX_PPT_TOOLS" },
        },
        {
          id: "MatchSize",
          label: "Match size",
          tip: "Give every selected object the first selected object's width and height.",
          icon: "match-size",
          action: { kind: "function", name: "PLSFIX_PPT_MATCH" },
        },
        {
          id: "SelectSimilar",
          label: "Select similar",
          tip: "Select every object on this slide with the same type and size as the selected one.",
          icon: "select-similar",
          action: { kind: "function", name: "PLSFIX_PPT_SIMILAR" },
        },
        {
          id: "Swap",
          label: "Swap",
          tip: "Swap the positions of exactly two selected objects.",
          icon: "swap",
          action: { kind: "function", name: "PLSFIX_PPT_SWAP" },
        },
        {
          id: "CaptureStyle",
          label: "Capture style",
          tip: "Smart Painter: remember the selected object's solid fill and outline.",
          icon: "capture-style",
          action: { kind: "function", name: "PLSFIX_PPT_CAPTURE" },
        },
        {
          id: "ApplyStyle",
          label: "Apply style",
          tip: "Smart Painter: paint the captured fill and outline over the selected objects.",
          icon: "apply-style",
          action: { kind: "function", name: "PLSFIX_PPT_PAINT" },
        },
      ],
    },
    {
      id: "PLSFIX.Group.Arrange",
      label: "Arrange",
      buttons: [
        {
          id: "AlignLeft",
          label: "Align left",
          tip: "Align the selected objects on their leftmost edge.",
          icon: "align-left",
          action: { kind: "function", name: "PLSFIX_PPT_ALIGN_LEFT" },
        },
        {
          id: "AlignCenter",
          label: "Align centre",
          tip: "Centre the selected objects horizontally on the selection.",
          icon: "align-center",
          action: { kind: "function", name: "PLSFIX_PPT_ALIGN_CENTER" },
        },
        {
          id: "AlignRight",
          label: "Align right",
          tip: "Align the selected objects on their rightmost edge.",
          icon: "align-right",
          action: { kind: "function", name: "PLSFIX_PPT_ALIGN_RIGHT" },
        },
        {
          id: "AlignTop",
          label: "Align top",
          tip: "Align the selected objects on their topmost edge.",
          icon: "align-top",
          action: { kind: "function", name: "PLSFIX_PPT_ALIGN_TOP" },
        },
        {
          id: "AlignMiddle",
          label: "Align middle",
          tip: "Centre the selected objects vertically on the selection.",
          icon: "align-middle",
          action: { kind: "function", name: "PLSFIX_PPT_ALIGN_MIDDLE" },
        },
        {
          id: "AlignBottom",
          label: "Align bottom",
          tip: "Align the selected objects on their bottom edge.",
          icon: "align-bottom",
          action: { kind: "function", name: "PLSFIX_PPT_ALIGN_BOTTOM" },
        },
        {
          id: "DistributeAcross",
          label: "Distribute across",
          tip: "Space three or more selected objects evenly from left to right, outer edges fixed.",
          icon: "distribute-across",
          action: { kind: "function", name: "PLSFIX_PPT_DIST_ACROSS" },
        },
        {
          id: "DistributeDown",
          label: "Distribute down",
          tip: "Space three or more selected objects evenly from top to bottom, outer edges fixed.",
          icon: "distribute-down",
          action: { kind: "function", name: "PLSFIX_PPT_DIST_DOWN" },
        },
      ],
    },
  ],
};

const packageVersion = pkg.version;

export const ADDIN: AddinSpec = {
  id: "FF1B34D8-DD7D-4B39-8FA9-6248CA09DB6E",
  version: `${packageVersion}.0`,
  provider: "Daniels Bendiks",
  displayName: "pls,fix",
  description:
    "Fast, consistent financial modelling tools for Excel and PowerPoint.",
  supportUrl: "https://dbautomatizacijas.com/modelis/support.html",
  appDomain: "https://dbautomatizacijas.com",
  tabLabel: "pls,fix",
  iconResids: {
    16: "PLSFIX.Icon.16",
    32: "PLSFIX.Icon.32",
    80: "PLSFIX.Icon.80",
  },
  hosts: [WORKBOOK_HOST, PRESENTATION_HOST],
};
