// The gates themselves, under test: the rules scripts/check-version.ts
// applies, and the npm wiring that decides whether a gate runs at all. A gate
// nothing calls, and a rule whose shape can no longer match anything this repo
// produces, both pass silently - which is the failure this file exists to
// catch.

import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import type { ConfigEnv, UserConfig, UserConfigExport } from "vite";
import pkg from "../package.json" with { type: "json" };
import { WORKBOOK_HOST } from "../manifest/spec";
import functionsConfig from "../vite.functions.config";
import paneConfig from "../vite.config";
import { versionProblems } from "./version-rules";

const VERSION = "2.1.18";

// A tree where every file agrees and only #app-version carries the version.
const CLEAN: Record<string, string> = {
  "server/Cargo.toml": `[package]\nname = "modelis"\nversion = "${VERSION}"\n`,
  "manifest.xml": `<Version>${VERSION}.0</Version>`,
  "manifest.prod.xml": `<Version>${VERSION}.0</Version>`,
  "taskpane.html": `<span id="app-version"></span>`,
  "pptpane.html": `<span id="app-version"></span>`,
  "src/main.ts": 'getElement("app-version").textContent = APP_VERSION;',
  "src/ppt/main.ts": 'getElement("app-version").textContent = APP_VERSION;',
};

function problems(overrides: Record<string, string> = {}): string[] {
  const tree = { ...CLEAN, ...overrides };
  return versionProblems((file) => tree[file] ?? "", VERSION);
}

describe("versionProblems", () => {
  it("passes a tree where only #app-version carries the version", () => {
    expect(problems()).toEqual([]);
  });

  // The regression: `npm version patch` writes 2.1.18, so the old \d{3} patch
  // rule could not fire on any version this repo will produce from here on.
  it("catches the two-digit patch npm version writes", () => {
    expect(
      problems({ "taskpane.html": `<footer>v${VERSION}</footer>` }),
    ).toEqual(["taskpane.html hard-codes a version; use #app-version"]);
  });

  it("catches the zero-padded form the footer renders", () => {
    expect(problems({ "pptpane.html": "<footer>v2.1.018</footer>" })).toEqual([
      "pptpane.html hard-codes a version; use #app-version",
    ]);
  });

  // A pane can hard-code its version in TypeScript just as easily as in HTML,
  // and that half was never looked at.
  it("catches a version literal in either pane's boot file", () => {
    expect(problems({ "src/main.ts": 'const shown = "v2.1.18";' })).toEqual([
      "src/main.ts hard-codes a version; use APP_VERSION",
    ]);
    expect(problems({ "src/ppt/main.ts": 'report("v2.")' })).toEqual([
      "src/ppt/main.ts hard-codes a version; use APP_VERSION",
    ]);
  });

  it("leaves a version the boot file interpolates alone", () => {
    expect(
      problems({ "src/main.ts": "const shown = `v${APP_VERSION}`;" }),
    ).toEqual([]);
  });

  // The bump script rewrites the [package] version only, so a dependency that
  // happens to be pinned at the same string must not stand in for it.
  it("reads the crate version from the [package] table alone", () => {
    expect(
      problems({
        "server/Cargo.toml":
          `[package]\nversion = "2.1.17"\n\n[dependencies]\n` +
          `serde = { version = "${VERSION}" }\n`,
      }),
    ).toEqual([`server/Cargo.toml is not ${VERSION}`]);
  });

  it("names a crate or manifest that fell behind", () => {
    expect(
      problems({
        "server/Cargo.toml": 'version = "2.1.17"',
        "manifest.prod.xml": "<Version>2.1.17.0</Version>",
      }),
    ).toEqual([
      `server/Cargo.toml is not ${VERSION}`,
      `manifest.prod.xml is not ${VERSION}.0`,
    ]);
  });

  // The rules against the real tree, so a file this gate reads cannot quietly
  // stop existing or start tripping it.
  it("passes the repository as it stands", () => {
    const read = (file: string) =>
      readFileSync(new URL(`../${file}`, import.meta.url), "utf8");
    expect(versionProblems(read, pkg.version)).toEqual([]);
  });
});

describe("npm run check", () => {
  const check = pkg.scripts.check;

  // manifest:check only diffs the generated bytes against the committed files:
  // it cannot see a manifest that is structurally wrong, because both sides
  // would be equally wrong. `validate` is the only schema check there is, and
  // it ran outside the gate until this landed.
  it("runs the manifest schema validator, after the generated-bytes gate", () => {
    expect(check).toContain("npm run validate");
    expect(check.indexOf("npm run manifest:check")).toBeLessThan(
      check.indexOf("npm run validate"),
    );
  });

  it("names only scripts that exist", () => {
    const named = [...check.matchAll(/npm run ([\w:-]+)/g)].map(
      (match) => match[1]!,
    );
    expect(named.length).toBeGreaterThan(5);
    for (const script of named) {
      expect(Object.keys(pkg.scripts)).toContain(script);
    }
  });
});

// A vite config is either the object or a function that produces one.
async function resolve(exported: UserConfigExport): Promise<UserConfig> {
  const env: ConfigEnv = { command: "build", mode: "production" };
  return typeof exported === "function" ? exported(env) : exported;
}

describe("the dev server serves what the manifest points at", () => {
  it("builds functions.js into the directory both the dev server and the pane build read", async () => {
    const functions = await resolve(functionsConfig);
    const pane = await resolve(paneConfig);
    // public/ is served at / in dev and copied into dist/ by the pane build,
    // so one file satisfies the dev sideload and production both.
    expect(functions.build?.outDir).toBe("public");
    expect(pane.publicDir).toBe("public");
    // ...and it is emitted once: the pane build copies public/, it does not
    // build the functions again.
    expect(pkg.scripts.build).toContain("npm run functions:js && vite build");
    expect(functions.publicDir).toBe(false);
    expect(functions.build?.emptyOutDir).toBe(false);
  });

  it("emits the file name the manifest publishes as the functions script", async () => {
    const functions = await resolve(functionsConfig);
    const lib = functions.build?.lib;
    const fileName =
      lib === undefined || lib === false ? undefined : lib.fileName;
    expect(
      typeof fileName === "function" ? fileName("iife", "index") : fileName,
    ).toBe(WORKBOOK_HOST.customFunctions?.scriptFile);
  });

  // The manifest points Office at /functions.js from the moment the sideload
  // starts; before these hooks, `npm start` served a 404 there and =SMT.ROUND
  // registered against nothing.
  it("builds the functions before any command that starts the dev server", () => {
    const scripts: Record<string, string> = pkg.scripts;
    for (const entry of ["dev", "dev-server", "start", "start:ppt"]) {
      expect(scripts[`pre${entry}`]).toBe("npm run functions:js");
    }
  });
});
